Configured non-headless to only open a single headed pyboy instance
thatguy11325/pokemonred_puffer pull request #9
Opened 2024-11-18 21:09 UTC by lloyd-delacroix

Set it up so that headless: False could be used on the main training loop only opening one headed instance of pyboy with the rest remaining headless. Allows an option for following a single sample for general observation minimizing performance impact. Previously, the behaviour when attempting to set headless: False without debug was a crash on launch.

2024-11-19 00:04 UTC, thatguy11325 reviewed
I'd instead make a new config list parameter, `headed` and if set will display the ids specified in the config.

2024-11-20 01:34 UTC, lloyd-delacroix commented
Updated to add new config item for selecting ids

2024-11-23 19:58 UTC, thatguy11325 requested changes
Some thoughts about how to change this a bit. We can bikeshed the names at a later time.

2024-11-23 19:58 UTC, thatguy11325 commented on config.yaml
> +    head_ids: #Which environment IDs to display in pyboy (env_id starts at 0 when serial in debug mode)
Hrm with this change, headless makes less sense. It can be controlled through head_ids.

2024-11-23 19:58 UTC, thatguy11325 commented on config.yaml
> +  disable_ai_actions: False
```suggestion
  headless: True
```
We don't want these settings to be true during normal runs.

2024-11-23 19:58 UTC, thatguy11325 commented on pokemonred_puffer/environment.py
> +            self.head_ids = {0} if self.debug else {1}
```suggestion
```

Not needed.

2024-11-23 19:58 UTC, thatguy11325 commented on pokemonred_puffer/environment.py
> +            #self.pyboy.set_emulation_speed(6)
```suggestion
```

However you should add set emulation speed if the env is in a head id.

2024-11-23 19:58 UTC, thatguy11325 commented on pokemonred_puffer/train.py
> +    defaults.env.debug = True if debug else False
```suggestion
```

Not really sure why this flag is needed. Even then you can set `defaults.env.debug` to `bool(debug)`

2025-02-27 04:41 UTC, closed without merging